### ISSUE TITLE
Configuração Inválida

### ISSUE THREAD

**Issue by lelis718** [DesignLiquido/pagseguro-dotnet#1]
A api quando pega a configuração do arquivo Web.Config não consegue pegar o valor das chaves de autorização resultando o código 401 unauthorized em todas as requisições.

Para simular, abra um projeto .Net framework 4.5.1 
Importe a biblioteca via Nuget
Coloque as configurações do PagSeguro no Web.Config conforme indicado na descrição da aplicação, colocando uma AppId e uma AppKey

Realize a chamada 
`var cred = PagSeguroConfiguration.ApplicationCredentials();`

No objeto criado você verá que as credenciais foram substituídas por 
`Uol.PagSeguro.Configuration.TextElement`

Impossibilitando a biblioteca de realizar requisições. 

![bug](https://cloud.githubusercontent.com/assets/477538/20191465/ae8d8d4e-a76c-11e6-9ae0-820338c15979.png)

**Comment by pablotdv** [comment]
@lelis718 obrigado por reportar o problema.

Acabei de comitar os ajustes no `ApplicationCredentials` que irá corrigir seu problema.

vou reportar ao @cigano para que ele atualizei o pacote no nuget.

**Comment by cigano** [comment]
Pacote publicado no NuGet com a correção, versão 2.7.1.
