### ISSUE TITLE
2017

### ISSUE THREAD

**Issue by ghost** [DesignLiquido/pagseguro-dotnet#2]
Olá amigo, o checkout transparente funciona hoje em dia?
Só instalar e rodar ou precisa de algum esforço adicional?
Digo isso porque aqui na empresa vamos precisar e estamos vendo as possíveis soluções. Abss!

**Comment by cigano** [comment]
Olá, Marco.

Sim, funciona. Vendi dois projetos com a tecnologia instalada. Qualquer
coisa é só falar.

Outro abraço!

2017-06-21 13:21 GMT-05:00 Marco Lima <notifications@github.com>:

**Comment by cigano** [comment]
Como isso não é uma issue de verdade, estou encerrando.
