### ISSUE TITLE
Pagamento

### ISSUE THREAD

**Issue by lGuzl** [DesignLiquido/pagseguro-dotnet#4]
Estou testando a rotina que vem junto no exemplo, para pagamento simples, para colocar em um aplicativo que estou desenvolvendo. 
No caso, alterei o xml para as configs ref. aos meus dados do sandbox.

Tanto com minhas configs, quanto com as que vem no exemplo, quando manda enviar, fica enviando... e nao há retorno do pagseguro.

Há algum problema com a biblioteca ou a rotina de pagamento?

Aproveito o tópico pra perguntar se existe uma forma de não ter dependência do xml de config?

**Comment by cigano** [comment]
@lGuzl [Leia o que escrevi aqui](https://github.com/DesignLiquido/pagseguro-dotnet#pre%C3%A2mbulo).

[A configuração pelo Web.config da aplicação tem um exemplo aqui](https://github.com/DesignLiquido/pagseguro-dotnet#configura%C3%A7%C3%A3o-usando-config-sections).
