### ISSUE TITLE
Token Cartão

### ISSUE THREAD

**Issue by lGuzl** [DesignLiquido/pagseguro-dotnet#5]
Bom dia,

Estou utilizando a biblioteca para integrar pagamentos em um app, que terá apenas pagamentos via cartão de crédito.

É possível a geração do token via c# diretamente? li em alguns lugares que somente via JS,ou seja, funcionaria apenas em apps web. 

Alguém tem algum exemplo?

**Comment by cigano** [comment]
Acredito que a geração do token seja possível apenas dentro da sua conta, no painel "Aplicações". Veja um exemplo de Token:

![image](https://user-images.githubusercontent.com/1513436/51792745-658dda00-217b-11e9-9524-e8b6e9e6f562.png)
